### PR TITLE
Feature b357

### PR DESCRIPTION
**Pull request by alpercakan**
### Description
What does this implement/fix? Explain your changes.

### Related Issues
...

### Other Comments
...

### Checklist
- [ ] Code runs
- [ ] Created tests (if applicable)
- [ ] All tests passing
- [ ] Extended the README and the documentation (if applicable)

### CODE REVIEW

**Comment by sercanersoy** [comment]
I think #360 does contain the changes in this PR. If so, we can close this.

**Comment by alpercakan** [comment]
No this is a prior PR, #360 is based on this. We should first merge this PR and then #360.

**Comment by sercanersoy** [comment]
This is the [diff](https://github.com/bounswe/bounswe2019group8/pull/360/files) for #360. It does contain the changes made in this PR because the branch ```feature-b358``` is derived from the branch ```feature-b357```.

**Comment by alpercakan** [comment]
Yeah I know. When we merge this, the other diff won't show the changes here.

**Comment by sercanersoy** [comment]
Alright, I am merging this PR. Thanks!

**Pull request merged**
